/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PerguntaResposta } from "./PerguntaResposta";
import { PerguntaRespostaCountArgs } from "./PerguntaRespostaCountArgs";
import { PerguntaRespostaFindManyArgs } from "./PerguntaRespostaFindManyArgs";
import { PerguntaRespostaFindUniqueArgs } from "./PerguntaRespostaFindUniqueArgs";
import { DeletePerguntaRespostaArgs } from "./DeletePerguntaRespostaArgs";
import { PerguntaRespostaService } from "../perguntaResposta.service";
@graphql.Resolver(() => PerguntaResposta)
export class PerguntaRespostaResolverBase {
  constructor(protected readonly service: PerguntaRespostaService) {}

  async _perguntaRespostasMeta(
    @graphql.Args() args: PerguntaRespostaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PerguntaResposta])
  async perguntaRespostas(
    @graphql.Args() args: PerguntaRespostaFindManyArgs
  ): Promise<PerguntaResposta[]> {
    return this.service.perguntaRespostas(args);
  }

  @graphql.Query(() => PerguntaResposta, { nullable: true })
  async perguntaResposta(
    @graphql.Args() args: PerguntaRespostaFindUniqueArgs
  ): Promise<PerguntaResposta | null> {
    const result = await this.service.perguntaResposta(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PerguntaResposta)
  async deletePerguntaResposta(
    @graphql.Args() args: DeletePerguntaRespostaArgs
  ): Promise<PerguntaResposta | null> {
    try {
      return await this.service.deletePerguntaResposta(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
