/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SessaoDeEstudo } from "./SessaoDeEstudo";
import { SessaoDeEstudoCountArgs } from "./SessaoDeEstudoCountArgs";
import { SessaoDeEstudoFindManyArgs } from "./SessaoDeEstudoFindManyArgs";
import { SessaoDeEstudoFindUniqueArgs } from "./SessaoDeEstudoFindUniqueArgs";
import { DeleteSessaoDeEstudoArgs } from "./DeleteSessaoDeEstudoArgs";
import { SessaoDeEstudoService } from "../sessaoDeEstudo.service";
@graphql.Resolver(() => SessaoDeEstudo)
export class SessaoDeEstudoResolverBase {
  constructor(protected readonly service: SessaoDeEstudoService) {}

  async _sessaoDeEstudosMeta(
    @graphql.Args() args: SessaoDeEstudoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SessaoDeEstudo])
  async sessaoDeEstudos(
    @graphql.Args() args: SessaoDeEstudoFindManyArgs
  ): Promise<SessaoDeEstudo[]> {
    return this.service.sessaoDeEstudos(args);
  }

  @graphql.Query(() => SessaoDeEstudo, { nullable: true })
  async sessaoDeEstudo(
    @graphql.Args() args: SessaoDeEstudoFindUniqueArgs
  ): Promise<SessaoDeEstudo | null> {
    const result = await this.service.sessaoDeEstudo(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SessaoDeEstudo)
  async deleteSessaoDeEstudo(
    @graphql.Args() args: DeleteSessaoDeEstudoArgs
  ): Promise<SessaoDeEstudo | null> {
    try {
      return await this.service.deleteSessaoDeEstudo(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
