/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, SessaoDeEstudo as PrismaSessaoDeEstudo } from "@prisma/client";

export class SessaoDeEstudoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SessaoDeEstudoCountArgs, "select">
  ): Promise<number> {
    return this.prisma.sessaoDeEstudo.count(args);
  }

  async sessaoDeEstudos(
    args: Prisma.SessaoDeEstudoFindManyArgs
  ): Promise<PrismaSessaoDeEstudo[]> {
    return this.prisma.sessaoDeEstudo.findMany(args);
  }
  async sessaoDeEstudo(
    args: Prisma.SessaoDeEstudoFindUniqueArgs
  ): Promise<PrismaSessaoDeEstudo | null> {
    return this.prisma.sessaoDeEstudo.findUnique(args);
  }
  async createSessaoDeEstudo(
    args: Prisma.SessaoDeEstudoCreateArgs
  ): Promise<PrismaSessaoDeEstudo> {
    return this.prisma.sessaoDeEstudo.create(args);
  }
  async updateSessaoDeEstudo(
    args: Prisma.SessaoDeEstudoUpdateArgs
  ): Promise<PrismaSessaoDeEstudo> {
    return this.prisma.sessaoDeEstudo.update(args);
  }
  async deleteSessaoDeEstudo(
    args: Prisma.SessaoDeEstudoDeleteArgs
  ): Promise<PrismaSessaoDeEstudo> {
    return this.prisma.sessaoDeEstudo.delete(args);
  }
}
